/* Generated by yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "FR.v:1.1-35.10" *)
module FR(carry, neg, agtb, aeqb, zero, clk, load, rst, carry_out, neg_out, agtb_out, aeqb_out, zero_out);
  (* src = "FR.v:5.11-5.15" *)
  wire _00_;
  (* src = "FR.v:13.16-13.24" *)
  wire _01_;
  (* src = "FR.v:4.11-4.15" *)
  wire _02_;
  (* src = "FR.v:12.16-12.24" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "FR.v:2.11-2.16" *)
  wire _14_;
  (* src = "FR.v:10.16-10.25" *)
  wire _15_;
  (* src = "FR.v:8.11-8.15" *)
  wire _16_;
  (* src = "FR.v:3.11-3.14" *)
  wire _17_;
  (* src = "FR.v:11.16-11.23" *)
  wire _18_;
  (* src = "FR.v:9.11-9.14" *)
  wire _19_;
  (* src = "FR.v:6.11-6.15" *)
  wire _20_;
  (* src = "FR.v:14.16-14.24" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  (* src = "FR.v:5.11-5.15" *)
  input aeqb;
  wire aeqb;
  (* src = "FR.v:13.16-13.24" *)
  output aeqb_out;
  wire aeqb_out;
  (* src = "FR.v:4.11-4.15" *)
  input agtb;
  wire agtb;
  (* src = "FR.v:12.16-12.24" *)
  output agtb_out;
  wire agtb_out;
  (* src = "FR.v:2.11-2.16" *)
  input carry;
  wire carry;
  (* src = "FR.v:10.16-10.25" *)
  output carry_out;
  wire carry_out;
  (* src = "FR.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "FR.v:8.11-8.15" *)
  input load;
  wire load;
  (* src = "FR.v:3.11-3.14" *)
  input neg;
  wire neg;
  (* src = "FR.v:11.16-11.23" *)
  output neg_out;
  wire neg_out;
  (* src = "FR.v:9.11-9.14" *)
  input rst;
  wire rst;
  (* src = "FR.v:6.11-6.15" *)
  input zero;
  wire zero;
  (* src = "FR.v:14.16-14.24" *)
  output zero_out;
  wire zero_out;
  sky130_fd_sc_hd__clkinv_1 _32_ (
    .A(_19_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _33_ (
    .A0(_21_),
    .A1(_20_),
    .S(_16_),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _34_ (
    .A0(_01_),
    .A1(_00_),
    .S(_16_),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _35_ (
    .A0(_03_),
    .A1(_02_),
    .S(_16_),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _36_ (
    .A0(_18_),
    .A1(_17_),
    .S(_16_),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _37_ (
    .A0(_15_),
    .A1(_14_),
    .S(_16_),
    .X(_09_)
  );
  sky130_fd_sc_hd__clkinv_1 _38_ (
    .A(_19_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _39_ (
    .A(_19_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _40_ (
    .A(_19_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _41_ (
    .A(_19_),
    .Y(_08_)
  );
  (* src = "FR.v:17.3-33.6" *)
  sky130_fd_sc_hd__dfrtp_1 _42_ (
    .CLK(clk),
    .D(_28_),
    .Q(neg_out),
    .RESET_B(_23_)
  );
  (* src = "FR.v:17.3-33.6" *)
  sky130_fd_sc_hd__dfrtp_1 _43_ (
    .CLK(clk),
    .D(_29_),
    .Q(agtb_out),
    .RESET_B(_24_)
  );
  (* src = "FR.v:17.3-33.6" *)
  sky130_fd_sc_hd__dfrtp_1 _44_ (
    .CLK(clk),
    .D(_30_),
    .Q(aeqb_out),
    .RESET_B(_25_)
  );
  (* src = "FR.v:17.3-33.6" *)
  sky130_fd_sc_hd__dfrtp_1 _45_ (
    .CLK(clk),
    .D(_31_),
    .Q(zero_out),
    .RESET_B(_26_)
  );
  (* src = "FR.v:17.3-33.6" *)
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_27_),
    .Q(carry_out),
    .RESET_B(_22_)
  );
  assign _21_ = zero_out;
  assign _20_ = zero;
  assign _16_ = load;
  assign _31_ = _13_;
  assign _01_ = aeqb_out;
  assign _00_ = aeqb;
  assign _30_ = _12_;
  assign _03_ = agtb_out;
  assign _02_ = agtb;
  assign _29_ = _11_;
  assign _18_ = neg_out;
  assign _17_ = neg;
  assign _28_ = _10_;
  assign _15_ = carry_out;
  assign _14_ = carry;
  assign _27_ = _09_;
  assign _19_ = rst;
  assign _22_ = _04_;
  assign _23_ = _05_;
  assign _24_ = _06_;
  assign _25_ = _07_;
  assign _26_ = _08_;
endmodule
