/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "CU.v:1.1-501.10" *)
module CU(t_state, opcode, carry, zero, neg, agtb, aeqb, load_A, load_B, load_PC, enable_PC, Write_RAM, load_MAR, load_FR, load_IR, ALU_sel, Bus_Select, TC_clear);
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _000_;
  (* src = "CU.v:50.3-499.4" *)
  wire _001_;
  (* src = "CU.v:50.3-499.4" *)
  wire _002_;
  (* src = "CU.v:50.3-499.4" *)
  wire _003_;
  (* src = "CU.v:50.3-499.4" *)
  wire _004_;
  (* src = "CU.v:50.3-499.4" *)
  wire _005_;
  (* src = "CU.v:50.3-499.4" *)
  wire _006_;
  (* src = "CU.v:50.3-499.4" *)
  wire _007_;
  (* src = "CU.v:50.3-499.4" *)
  wire _008_;
  (* src = "CU.v:50.3-499.4" *)
  wire _009_;
  (* src = "CU.v:50.3-499.4" *)
  wire _010_;
  (* src = "CU.v:50.3-499.4" *)
  wire _011_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _012_;
  (* src = "CU.v:50.3-499.4" *)
  wire _013_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _014_;
  (* src = "CU.v:50.3-499.4" *)
  wire _015_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _016_;
  (* src = "CU.v:50.3-499.4" *)
  wire _017_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _018_;
  (* src = "CU.v:50.3-499.4" *)
  wire _019_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _020_;
  (* src = "CU.v:50.3-499.4" *)
  wire _021_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _022_;
  (* src = "CU.v:50.3-499.4" *)
  wire _023_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _024_;
  (* src = "CU.v:50.3-499.4" *)
  wire _025_;
  (* src = "CU.v:50.3-499.4" *)
  wire [2:0] _026_;
  (* src = "CU.v:50.3-499.4" *)
  wire _027_;
  (* src = "CU.v:15.16-15.25" *)
  wire _028_;
  (* src = "CU.v:10.11-10.15" *)
  wire _029_;
  (* src = "CU.v:9.11-9.15" *)
  wire _030_;
  (* src = "CU.v:6.11-6.16" *)
  wire _031_;
  (* src = "CU.v:14.16-14.25" *)
  wire _032_;
  (* src = "CU.v:17.16-17.23" *)
  wire _033_;
  (* src = "CU.v:16.16-16.24" *)
  wire _034_;
  (* src = "CU.v:8.11-8.14" *)
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  (* src = "CU.v:5.17-5.23" *)
  wire _080_;
  (* src = "CU.v:5.17-5.23" *)
  wire _081_;
  (* src = "CU.v:5.17-5.23" *)
  wire _082_;
  (* src = "CU.v:5.17-5.23" *)
  wire _083_;
  (* src = "CU.v:5.17-5.23" *)
  wire _084_;
  (* src = "CU.v:5.17-5.23" *)
  wire _085_;
  (* src = "CU.v:5.17-5.23" *)
  wire _086_;
  (* src = "CU.v:5.17-5.23" *)
  wire _087_;
  (* src = "CU.v:4.32-4.39" *)
  wire _088_;
  (* src = "CU.v:4.32-4.39" *)
  wire _089_;
  (* src = "CU.v:4.32-4.39" *)
  wire _090_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _091_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _092_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _093_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _094_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _095_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _096_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _097_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _098_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _099_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _100_;
  (* src = "CU.v:7.11-7.15" *)
  wire _101_;
  (* src = "CU.v:452.17-452.38" *)
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire [3:0] _115_;
  wire [1:0] _116_;
  wire _117_;
  wire [3:0] _118_;
  wire [1:0] _119_;
  wire _120_;
  wire [3:0] _121_;
  wire [1:0] _122_;
  wire _123_;
  wire [3:0] _124_;
  wire [1:0] _125_;
  wire _126_;
  wire [3:0] _127_;
  wire [1:0] _128_;
  wire _129_;
  wire [3:0] _130_;
  wire [1:0] _131_;
  wire _132_;
  wire [3:0] _133_;
  wire [1:0] _134_;
  wire _135_;
  wire [3:0] _136_;
  wire [1:0] _137_;
  wire _138_;
  wire [3:0] _139_;
  wire [1:0] _140_;
  wire _141_;
  wire _142_;
  wire [1:0] _143_;
  wire _144_;
  wire [3:0] _145_;
  wire [1:0] _146_;
  wire _147_;
  wire [3:0] _148_;
  wire [1:0] _149_;
  wire _150_;
  wire [3:0] _151_;
  wire [1:0] _152_;
  wire _153_;
  wire [3:0] _154_;
  wire [1:0] _155_;
  wire _156_;
  wire [3:0] _157_;
  wire [1:0] _158_;
  wire _159_;
  wire _160_;
  wire [3:0] _161_;
  wire [1:0] _162_;
  wire _163_;
  wire [10:0] _164_;
  wire [5:0] _165_;
  wire [2:0] _166_;
  wire _167_;
  wire _168_;
  wire [3:0] _169_;
  wire [1:0] _170_;
  wire _171_;
  wire [3:0] _172_;
  wire [1:0] _173_;
  wire _174_;
  wire _175_;
  wire [3:0] _176_;
  wire [1:0] _177_;
  wire _178_;
  wire [3:0] _179_;
  wire [1:0] _180_;
  wire _181_;
  wire _182_;
  wire [3:0] _183_;
  wire [1:0] _184_;
  wire _185_;
  wire [3:0] _186_;
  wire [1:0] _187_;
  wire _188_;
  wire [3:0] _189_;
  wire [1:0] _190_;
  wire _191_;
  wire [3:0] _192_;
  wire [1:0] _193_;
  wire _194_;
  wire [3:0] _195_;
  wire [1:0] _196_;
  wire _197_;
  wire [8:0] _198_;
  wire [4:0] _199_;
  wire [1:0] _200_;
  wire _201_;
  wire _202_;
  wire [3:0] _203_;
  wire [1:0] _204_;
  wire _205_;
  wire [3:0] _206_;
  wire [1:0] _207_;
  wire _208_;
  wire _209_;
  wire [3:0] _210_;
  wire [1:0] _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire [2:0] _216_;
  wire [1:0] _217_;
  wire _218_;
  wire [2:0] _219_;
  wire [1:0] _220_;
  wire _221_;
  wire [2:0] _222_;
  wire [1:0] _223_;
  wire _224_;
  wire [2:0] _225_;
  wire [1:0] _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire [1:0] _230_;
  wire _231_;
  wire [1:0] _232_;
  wire _233_;
  wire [1:0] _234_;
  wire _235_;
  wire [1:0] _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire [2:0] _242_;
  wire [2:0] _243_;
  wire [7:0] _244_;
  wire [7:0] _245_;
  wire [7:0] _246_;
  wire [7:0] _247_;
  wire [7:0] _248_;
  wire [7:0] _249_;
  wire [7:0] _250_;
  wire [7:0] _251_;
  wire [7:0] _252_;
  wire [7:0] _253_;
  wire [7:0] _254_;
  wire [7:0] _255_;
  wire [7:0] _256_;
  wire [7:0] _257_;
  wire [7:0] _258_;
  wire [7:0] _259_;
  wire [7:0] _260_;
  wire [7:0] _261_;
  wire [7:0] _262_;
  wire [7:0] _263_;
  wire [7:0] _264_;
  wire [7:0] _265_;
  wire [7:0] _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  (* src = "CU.v:452.17-452.26" *)
  wire _292_;
  (* src = "CU.v:452.29-452.38" *)
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:569.20-569.21" *)
  wire _311_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _312_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _313_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [1:0] _314_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _315_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _316_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:569.20-569.21" *)
  wire [2:0] _327_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [11:0] _328_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [11:0] _329_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [3:0] _330_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [3:0] _331_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [3:0] _332_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [3:0] _333_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _334_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _335_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:569.20-569.21" *)
  wire _336_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _337_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _338_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [1:0] _339_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _340_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _341_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _342_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:569.20-569.21" *)
  wire [2:0] _343_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [20:0] _344_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [20:0] _345_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [6:0] _346_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [6:0] _347_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [6:0] _348_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [6:0] _349_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _350_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _351_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:569.20-569.21" *)
  wire _352_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [8:0] _353_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [8:0] _354_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [8:0] _355_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [8:0] _356_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _357_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _358_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:569.20-569.21" *)
  wire _359_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [1:0] _360_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [1:0] _361_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:589.23-589.33" *)
  wire [1:0] _362_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _363_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _364_;
  (* force_downto = 32'd1 *)
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _365_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _366_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _367_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _368_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _369_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _370_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _371_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _372_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _373_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _374_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _375_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _376_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _377_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _378_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire [2:0] _379_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _380_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _381_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _382_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _383_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _384_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _385_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _386_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _387_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _388_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _389_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _390_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire [2:0] _391_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _392_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _393_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _394_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _395_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire [2:0] _396_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _397_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _398_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _399_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _400_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _401_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _402_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _403_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _404_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _405_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _406_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _407_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _408_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _409_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)
  wire _410_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)
  wire _411_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _412_;
  (* src = "CU.v:0.0-0.0|CU.v:66.5-497.9|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *)
  wire _413_;
  (* src = "CU.v:19.22-19.29" *)
  output [2:0] ALU_sel;
  wire [2:0] ALU_sel;
  (* src = "CU.v:20.22-20.32" *)
  output [2:0] Bus_Select;
  wire [2:0] Bus_Select;
  (* src = "CU.v:21.16-21.24" *)
  output TC_clear;
  wire TC_clear;
  (* src = "CU.v:15.16-15.25" *)
  output Write_RAM;
  wire Write_RAM;
  (* src = "CU.v:10.11-10.15" *)
  input aeqb;
  wire aeqb;
  (* src = "CU.v:9.11-9.15" *)
  input agtb;
  wire agtb;
  (* src = "CU.v:6.11-6.16" *)
  input carry;
  wire carry;
  (* src = "CU.v:14.16-14.25" *)
  output enable_PC;
  wire enable_PC;
  (* src = "CU.v:11.16-11.22" *)
  output load_A;
  wire load_A;
  (* src = "CU.v:12.16-12.22" *)
  output load_B;
  wire load_B;
  (* src = "CU.v:17.16-17.23" *)
  output load_FR;
  wire load_FR;
  (* src = "CU.v:18.16-18.23" *)
  output load_IR;
  wire load_IR;
  (* src = "CU.v:16.16-16.24" *)
  output load_MAR;
  wire load_MAR;
  (* src = "CU.v:13.16-13.23" *)
  output load_PC;
  wire load_PC;
  (* src = "CU.v:8.11-8.14" *)
  input neg;
  wire neg;
  (* src = "CU.v:5.17-5.23" *)
  input [7:0] opcode;
  wire [7:0] opcode;
  (* src = "CU.v:4.32-4.39" *)
  input [2:0] t_state;
  wire [2:0] t_state;
  (* src = "CU.v:7.11-7.15" *)
  input zero;
  wire zero;
  sky130_fd_sc_hd__nor2_1 _414_ (
    .A(_089_),
    .B(_090_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__and2_0 _415_ (
    .A(_088_),
    .B(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _416_ (
    .A(_088_),
    .B(_036_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor4b_1 _417_ (
    .A(_086_),
    .B(_084_),
    .C(_087_),
    .D_N(_085_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _418_ (
    .A(_081_),
    .B(_080_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2b_1 _419_ (
    .A_N(_083_),
    .B(_082_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _420_ (
    .A(_041_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nor3b_1 _421_ (
    .A(_041_),
    .B(_081_),
    .C_N(_080_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3b_1 _422_ (
    .A(_080_),
    .B(_041_),
    .C_N(_081_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(_081_),
    .B(_080_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _424_ (
    .A(_083_),
    .B(_082_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _425_ (
    .A(_039_),
    .SLEEP(_083_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand2b_1 _426_ (
    .A_N(_083_),
    .B(_039_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(_038_),
    .B(_048_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__or3b_1 _428_ (
    .A(_088_),
    .B(_090_),
    .C_N(_089_),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor4_1 _429_ (
    .A(_086_),
    .B(_085_),
    .C(_084_),
    .D(_087_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand4b_1 _430_ (
    .A_N(_083_),
    .B(_082_),
    .C(_040_),
    .D(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand4_1 _431_ (
    .A(_081_),
    .B(_080_),
    .C(_046_),
    .D(_050_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _432_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nand2b_1 _433_ (
    .A_N(_049_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _434_ (
    .A1(_038_),
    .A2(_048_),
    .B1(_054_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_1 _435_ (
    .A(_044_),
    .B(_050_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__o21ai_0 _436_ (
    .A1(_049_),
    .A2(_055_),
    .B1(_054_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o2111a_1 _437_ (
    .A1(_042_),
    .A2(_046_),
    .B1(_081_),
    .C1(_037_),
    .D1(_039_),
    .X(_097_)
  );
  sky130_fd_sc_hd__and4b_1 _438_ (
    .A_N(_083_),
    .B(_080_),
    .C(_037_),
    .D(_039_),
    .X(_096_)
  );
  sky130_fd_sc_hd__nor4b_1 _439_ (
    .A(_083_),
    .B(_082_),
    .C(_080_),
    .D_N(_081_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand3_1 _440_ (
    .A(_037_),
    .B(_050_),
    .C(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(_049_),
    .A2(_051_),
    .B1(_057_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4b_1 _442_ (
    .A(_085_),
    .B(_084_),
    .C(_087_),
    .D_N(_086_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__or4b_1 _443_ (
    .A(_085_),
    .B(_084_),
    .C(_087_),
    .D_N(_086_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nor4_1 _444_ (
    .A(_083_),
    .B(_082_),
    .C(_045_),
    .D(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor4_1 _445_ (
    .A(_031_),
    .B(_041_),
    .C(_045_),
    .D(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a21oi_1 _446_ (
    .A1(_029_),
    .A2(_060_),
    .B1(_061_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor4b_1 _447_ (
    .A(_083_),
    .B(_082_),
    .C(_081_),
    .D_N(_080_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand3_1 _448_ (
    .A(_031_),
    .B(_058_),
    .C(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_1 _449_ (
    .A(_081_),
    .B(_080_),
    .C(_059_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a32oi_1 _450_ (
    .A1(_035_),
    .A2(_044_),
    .A3(_058_),
    .B1(_065_),
    .B2(_046_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand4_1 _451_ (
    .A(_030_),
    .B(_040_),
    .C(_042_),
    .D(_058_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(_043_),
    .B(_058_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__o311a_1 _453_ (
    .A1(_029_),
    .A2(_030_),
    .A3(_068_),
    .B1(_067_),
    .C1(_066_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand4b_1 _454_ (
    .A_N(_082_),
    .B(_040_),
    .C(_058_),
    .D(_083_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _455_ (
    .A(_101_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a31oi_1 _456_ (
    .A1(_101_),
    .A2(_056_),
    .A3(_058_),
    .B1(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a41oi_1 _457_ (
    .A1(_062_),
    .A2(_064_),
    .A3(_069_),
    .A4(_072_),
    .B1(_038_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__and3_1 _458_ (
    .A(_037_),
    .B(_039_),
    .C(_042_),
    .X(_098_)
  );
  sky130_fd_sc_hd__a21oi_1 _459_ (
    .A1(_050_),
    .A2(_063_),
    .B1(_047_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o22ai_1 _460_ (
    .A1(_049_),
    .A2(_052_),
    .B1(_073_),
    .B2(_038_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__o21ai_0 _461_ (
    .A1(_056_),
    .A2(_063_),
    .B1(_050_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _462_ (
    .A(_038_),
    .B(_074_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _463_ (
    .A(_041_),
    .B(_059_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _464_ (
    .A(_070_),
    .B(_074_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__a2111oi_0 _465_ (
    .A1(_046_),
    .A2(_058_),
    .B1(_075_),
    .C1(_076_),
    .D1(_047_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21a_1 _466_ (
    .A1(_043_),
    .A2(_044_),
    .B1(_050_),
    .X(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _467_ (
    .A(_053_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o22ai_1 _468_ (
    .A1(_038_),
    .A2(_077_),
    .B1(_079_),
    .B2(_049_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a2111oi_0 _469_ (
    .A1(_077_),
    .A2(_079_),
    .B1(_089_),
    .C1(_088_),
    .D1(_090_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _470_ (
    .A(_038_),
    .B(_079_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _471_ (
    .A(_078_),
    .SLEEP(_049_),
    .X(_028_)
  );
  assign load_IR = enable_PC;
  assign _311_ = 1'h0;
  assign _312_ = { _013_, _001_ };
  assign _315_ = { _104_, _103_ };
  assign _316_ = TC_clear;
  assign TC_clear = _370_;
  assign _313_[0] = _366_;
  assign _313_[1] = _367_;
  assign _314_[0] = _313_[0];
  assign _314_[1] = _313_[1];
  assign _317_ = _368_;
  assign _327_ = 3'h0;
  assign _328_ = { _012_, _016_, _020_, _000_ };
  assign _333_ = { _107_, _106_, _302_, _105_ };
  assign _334_ = Bus_Select;
  assign Bus_Select = _379_;
  assign _329_[2:0] = _371_;
  assign _329_[5:3] = _372_;
  assign _329_[8:6] = _373_;
  assign _329_[11:9] = _374_;
  assign _330_[0] = _329_[0];
  assign _330_[1] = _329_[3];
  assign _330_[2] = _329_[6];
  assign _330_[3] = _329_[9];
  assign _335_[0] = _375_;
  assign _331_[0] = _329_[1];
  assign _331_[1] = _329_[4];
  assign _331_[2] = _329_[7];
  assign _331_[3] = _329_[10];
  assign _335_[1] = _376_;
  assign _332_[0] = _329_[2];
  assign _332_[1] = _329_[5];
  assign _332_[2] = _329_[8];
  assign _332_[3] = _329_[11];
  assign _335_[2] = _377_;
  assign _336_ = 1'h0;
  assign _337_ = { _013_, _001_ };
  assign _340_ = { _308_, _109_ };
  assign _341_ = load_A;
  assign load_A = _384_;
  assign _338_[0] = _380_;
  assign _338_[1] = _381_;
  assign _339_[0] = _338_[0];
  assign _339_[1] = _338_[1];
  assign _342_ = _382_;
  assign _343_ = 3'h0;
  assign _344_ = { _014_, _000_, _018_, _012_, _022_, _024_, _026_ };
  assign _349_ = { _299_, _298_, _295_, _326_, _325_, _324_, _323_ };
  assign _350_ = ALU_sel;
  assign ALU_sel = _396_;
  assign _345_[2:0] = _385_;
  assign _345_[5:3] = _386_;
  assign _345_[8:6] = _387_;
  assign _345_[11:9] = _388_;
  assign _345_[14:12] = _389_;
  assign _345_[17:15] = _390_;
  assign _345_[20:18] = _391_;
  assign _346_[0] = _345_[0];
  assign _346_[1] = _345_[3];
  assign _346_[2] = _345_[6];
  assign _346_[3] = _345_[9];
  assign _346_[4] = _345_[12];
  assign _346_[5] = _345_[15];
  assign _346_[6] = _345_[18];
  assign _351_[0] = _392_;
  assign _347_[0] = _345_[1];
  assign _347_[1] = _345_[4];
  assign _347_[2] = _345_[7];
  assign _347_[3] = _345_[10];
  assign _347_[4] = _345_[13];
  assign _347_[5] = _345_[16];
  assign _347_[6] = _345_[19];
  assign _351_[1] = _393_;
  assign _348_[0] = _345_[2];
  assign _348_[1] = _345_[5];
  assign _348_[2] = _345_[8];
  assign _348_[3] = _345_[11];
  assign _348_[4] = _345_[14];
  assign _348_[5] = _345_[17];
  assign _348_[6] = _345_[20];
  assign _351_[2] = _394_;
  assign _352_ = 1'h0;
  assign _353_ = { _001_, _015_, _019_, _023_, _027_, _004_, _006_, _008_, _010_ };
  assign _356_ = { _322_, _321_, _320_, _319_, _307_, _300_, _296_, _318_, _303_ };
  assign _357_ = load_PC;
  assign load_PC = _408_;
  assign _354_[0] = _397_;
  assign _354_[1] = _398_;
  assign _354_[2] = _399_;
  assign _354_[3] = _400_;
  assign _354_[4] = _401_;
  assign _354_[5] = _402_;
  assign _354_[6] = _403_;
  assign _354_[7] = _404_;
  assign _354_[8] = _405_;
  assign _355_[0] = _354_[0];
  assign _355_[1] = _354_[1];
  assign _355_[2] = _354_[2];
  assign _355_[3] = _354_[3];
  assign _355_[4] = _354_[4];
  assign _355_[5] = _354_[5];
  assign _355_[6] = _354_[6];
  assign _355_[7] = _354_[7];
  assign _355_[8] = _354_[8];
  assign _358_ = _406_;
  assign _359_ = 1'h0;
  assign _360_ = { _001_, _013_ };
  assign _363_ = { _309_, _306_ };
  assign _364_ = load_B;
  assign load_B = _413_;
  assign _361_[0] = _409_;
  assign _361_[1] = _410_;
  assign _362_[0] = _361_[0];
  assign _362_[1] = _361_[1];
  assign _365_ = _411_;
  assign _379_[1] = _093_;
  assign _379_[0] = _092_;
  assign _396_[1] = _097_;
  assign _396_[0] = _096_;
  assign _086_ = opcode[6];
  assign _085_ = opcode[5];
  assign _084_ = opcode[4];
  assign _083_ = opcode[3];
  assign _082_ = opcode[2];
  assign _081_ = opcode[1];
  assign _080_ = opcode[0];
  assign _087_ = opcode[7];
  assign _413_ = _100_;
  assign _408_ = _099_;
  assign _396_[2] = _098_;
  assign _384_ = _095_;
  assign _379_[2] = _094_;
  assign _370_ = _091_;
  assign _089_ = t_state[1];
  assign _088_ = t_state[0];
  assign _090_ = t_state[2];
  assign _029_ = aeqb;
  assign _030_ = agtb;
  assign _101_ = zero;
  assign _035_ = neg;
  assign enable_PC = _032_;
  assign load_FR = _033_;
  assign load_MAR = _034_;
  assign Write_RAM = _028_;
  assign _031_ = carry;
endmodule
