/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "A_Register.v:1.1-21.10" *)
module A_Register(in, loadA, rst, clk, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _16_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _17_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _18_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _19_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _20_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _21_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _22_;
  (* src = "A_Register.v:4.23-4.25" *)
  wire _23_;
  (* src = "A_Register.v:5.11-5.16" *)
  wire _24_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _25_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _26_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _27_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _28_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _29_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _30_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _31_;
  (* src = "A_Register.v:8.28-8.31" *)
  wire _32_;
  (* src = "A_Register.v:6.11-6.14" *)
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  (* src = "A_Register.v:7.11-7.14" *)
  input clk;
  wire clk;
  (* src = "A_Register.v:4.23-4.25" *)
  input [7:0] in;
  wire [7:0] in;
  (* src = "A_Register.v:5.11-5.16" *)
  input loadA;
  wire loadA;
  (* src = "A_Register.v:8.28-8.31" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "A_Register.v:6.11-6.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _50_ (
    .A(_33_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _51_ (
    .A0(_32_),
    .A1(_23_),
    .S(_24_),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _52_ (
    .A0(_25_),
    .A1(_16_),
    .S(_24_),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _53_ (
    .A0(_26_),
    .A1(_17_),
    .S(_24_),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _54_ (
    .A0(_27_),
    .A1(_18_),
    .S(_24_),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _55_ (
    .A0(_28_),
    .A1(_19_),
    .S(_24_),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _56_ (
    .A0(_29_),
    .A1(_20_),
    .S(_24_),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _57_ (
    .A0(_30_),
    .A1(_21_),
    .S(_24_),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _58_ (
    .A0(_31_),
    .A1(_22_),
    .S(_24_),
    .X(_14_)
  );
  sky130_fd_sc_hd__clkinv_1 _59_ (
    .A(_33_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _60_ (
    .A(_33_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _61_ (
    .A(_33_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _62_ (
    .A(_33_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _63_ (
    .A(_33_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _64_ (
    .A(_33_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _65_ (
    .A(_33_),
    .Y(_05_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _66_ (
    .CLK(clk),
    .D(_46_),
    .Q(out[0]),
    .RESET_B(_38_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _67_ (
    .CLK(clk),
    .D(_45_),
    .Q(out[1]),
    .RESET_B(_37_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _68_ (
    .CLK(clk),
    .D(_44_),
    .Q(out[2]),
    .RESET_B(_36_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _69_ (
    .CLK(clk),
    .D(_43_),
    .Q(out[3]),
    .RESET_B(_35_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _70_ (
    .CLK(clk),
    .D(_42_),
    .Q(out[4]),
    .RESET_B(_34_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _71_ (
    .CLK(clk),
    .D(_49_),
    .Q(out[5]),
    .RESET_B(_41_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _72_ (
    .CLK(clk),
    .D(_48_),
    .Q(out[6]),
    .RESET_B(_40_)
  );
  (* src = "A_Register.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(clk),
    .D(_47_),
    .Q(out[7]),
    .RESET_B(_39_)
  );
  assign _32_ = out[7];
  assign _23_ = in[7];
  assign _24_ = loadA;
  assign _47_ = _13_;
  assign _25_ = out[0];
  assign _16_ = in[0];
  assign _46_ = _12_;
  assign _26_ = out[1];
  assign _17_ = in[1];
  assign _45_ = _11_;
  assign _27_ = out[2];
  assign _18_ = in[2];
  assign _44_ = _10_;
  assign _28_ = out[3];
  assign _19_ = in[3];
  assign _43_ = _09_;
  assign _29_ = out[4];
  assign _20_ = in[4];
  assign _42_ = _08_;
  assign _30_ = out[5];
  assign _21_ = in[5];
  assign _49_ = _15_;
  assign _31_ = out[6];
  assign _22_ = in[6];
  assign _48_ = _14_;
  assign _33_ = rst;
  assign _40_ = _06_;
  assign _41_ = _07_;
  assign _34_ = _00_;
  assign _35_ = _01_;
  assign _36_ = _02_;
  assign _37_ = _03_;
  assign _38_ = _04_;
  assign _39_ = _05_;
endmodule
