/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "IR.v:1.1-21.10" *)
module IR(in, load, clk, rst, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  (* src = "IR.v:4.24-4.26" *)
  wire _032_;
  (* src = "IR.v:4.24-4.26" *)
  wire _033_;
  (* src = "IR.v:4.24-4.26" *)
  wire _034_;
  (* src = "IR.v:4.24-4.26" *)
  wire _035_;
  (* src = "IR.v:4.24-4.26" *)
  wire _036_;
  (* src = "IR.v:4.24-4.26" *)
  wire _037_;
  (* src = "IR.v:4.24-4.26" *)
  wire _038_;
  (* src = "IR.v:4.24-4.26" *)
  wire _039_;
  (* src = "IR.v:4.24-4.26" *)
  wire _040_;
  (* src = "IR.v:4.24-4.26" *)
  wire _041_;
  (* src = "IR.v:4.24-4.26" *)
  wire _042_;
  (* src = "IR.v:4.24-4.26" *)
  wire _043_;
  (* src = "IR.v:4.24-4.26" *)
  wire _044_;
  (* src = "IR.v:4.24-4.26" *)
  wire _045_;
  (* src = "IR.v:4.24-4.26" *)
  wire _046_;
  (* src = "IR.v:4.24-4.26" *)
  wire _047_;
  (* src = "IR.v:5.11-5.15" *)
  wire _048_;
  (* src = "IR.v:8.29-8.32" *)
  wire _049_;
  (* src = "IR.v:8.29-8.32" *)
  wire _050_;
  (* src = "IR.v:8.29-8.32" *)
  wire _051_;
  (* src = "IR.v:8.29-8.32" *)
  wire _052_;
  (* src = "IR.v:8.29-8.32" *)
  wire _053_;
  (* src = "IR.v:8.29-8.32" *)
  wire _054_;
  (* src = "IR.v:8.29-8.32" *)
  wire _055_;
  (* src = "IR.v:8.29-8.32" *)
  wire _056_;
  (* src = "IR.v:8.29-8.32" *)
  wire _057_;
  (* src = "IR.v:8.29-8.32" *)
  wire _058_;
  (* src = "IR.v:8.29-8.32" *)
  wire _059_;
  (* src = "IR.v:8.29-8.32" *)
  wire _060_;
  (* src = "IR.v:8.29-8.32" *)
  wire _061_;
  (* src = "IR.v:8.29-8.32" *)
  wire _062_;
  (* src = "IR.v:8.29-8.32" *)
  wire _063_;
  (* src = "IR.v:8.29-8.32" *)
  wire _064_;
  (* src = "IR.v:7.11-7.14" *)
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  (* src = "IR.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "IR.v:4.24-4.26" *)
  input [15:0] in;
  wire [15:0] in;
  (* src = "IR.v:5.11-5.15" *)
  input load;
  wire load;
  (* src = "IR.v:8.29-8.32" *)
  output [15:0] out;
  wire [15:0] out;
  (* src = "IR.v:7.11-7.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _098_ (
    .A(_065_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(_055_),
    .A1(_038_),
    .S(_048_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(_049_),
    .A1(_032_),
    .S(_048_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(_056_),
    .A1(_039_),
    .S(_048_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(_057_),
    .A1(_040_),
    .S(_048_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(_058_),
    .A1(_041_),
    .S(_048_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(_059_),
    .A1(_042_),
    .S(_048_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(_060_),
    .A1(_043_),
    .S(_048_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(_061_),
    .A1(_044_),
    .S(_048_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(_062_),
    .A1(_045_),
    .S(_048_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(_063_),
    .A1(_046_),
    .S(_048_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _109_ (
    .A0(_064_),
    .A1(_047_),
    .S(_048_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(_050_),
    .A1(_033_),
    .S(_048_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(_051_),
    .A1(_034_),
    .S(_048_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(_052_),
    .A1(_035_),
    .S(_048_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(_053_),
    .A1(_036_),
    .S(_048_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(_054_),
    .A1(_037_),
    .S(_048_),
    .X(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _115_ (
    .A(_065_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _116_ (
    .A(_065_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(_065_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(_065_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(_065_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _120_ (
    .A(_065_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _121_ (
    .A(_065_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _122_ (
    .A(_065_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _123_ (
    .A(_065_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _124_ (
    .A(_065_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _125_ (
    .A(_065_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _126_ (
    .A(_065_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _127_ (
    .A(_065_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _128_ (
    .A(_065_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _129_ (
    .A(_065_),
    .Y(_015_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk),
    .D(_096_),
    .Q(out[0]),
    .RESET_B(_080_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk),
    .D(_095_),
    .Q(out[1]),
    .RESET_B(_079_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk),
    .D(_094_),
    .Q(out[2]),
    .RESET_B(_078_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk),
    .D(_093_),
    .Q(out[3]),
    .RESET_B(_077_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk),
    .D(_092_),
    .Q(out[4]),
    .RESET_B(_076_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk),
    .D(_091_),
    .Q(out[5]),
    .RESET_B(_075_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(clk),
    .D(_090_),
    .Q(out[6]),
    .RESET_B(_074_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(clk),
    .D(_089_),
    .Q(out[7]),
    .RESET_B(_073_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(clk),
    .D(_088_),
    .Q(out[8]),
    .RESET_B(_072_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk),
    .D(_087_),
    .Q(out[9]),
    .RESET_B(_071_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk),
    .D(_086_),
    .Q(out[10]),
    .RESET_B(_070_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk),
    .D(_085_),
    .Q(out[11]),
    .RESET_B(_069_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk),
    .D(_084_),
    .Q(out[12]),
    .RESET_B(_068_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk),
    .D(_083_),
    .Q(out[13]),
    .RESET_B(_067_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(_082_),
    .Q(out[14]),
    .RESET_B(_066_)
  );
  (* src = "IR.v:11.3-19.6" *)
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(clk),
    .D(_097_),
    .Q(out[15]),
    .RESET_B(_081_)
  );
  assign _055_ = out[15];
  assign _038_ = in[15];
  assign _048_ = load;
  assign _097_ = _031_;
  assign _049_ = out[0];
  assign _032_ = in[0];
  assign _096_ = _030_;
  assign _056_ = out[1];
  assign _039_ = in[1];
  assign _095_ = _029_;
  assign _057_ = out[2];
  assign _040_ = in[2];
  assign _094_ = _028_;
  assign _058_ = out[3];
  assign _041_ = in[3];
  assign _093_ = _027_;
  assign _059_ = out[4];
  assign _042_ = in[4];
  assign _092_ = _026_;
  assign _060_ = out[5];
  assign _043_ = in[5];
  assign _091_ = _025_;
  assign _061_ = out[6];
  assign _044_ = in[6];
  assign _090_ = _024_;
  assign _062_ = out[7];
  assign _045_ = in[7];
  assign _089_ = _023_;
  assign _063_ = out[8];
  assign _046_ = in[8];
  assign _088_ = _022_;
  assign _064_ = out[9];
  assign _047_ = in[9];
  assign _087_ = _021_;
  assign _050_ = out[10];
  assign _033_ = in[10];
  assign _086_ = _020_;
  assign _051_ = out[11];
  assign _034_ = in[11];
  assign _085_ = _019_;
  assign _052_ = out[12];
  assign _035_ = in[12];
  assign _084_ = _018_;
  assign _053_ = out[13];
  assign _036_ = in[13];
  assign _083_ = _017_;
  assign _054_ = out[14];
  assign _037_ = in[14];
  assign _082_ = _016_;
  assign _065_ = rst;
  assign _066_ = _000_;
  assign _067_ = _001_;
  assign _068_ = _002_;
  assign _069_ = _003_;
  assign _070_ = _004_;
  assign _071_ = _005_;
  assign _072_ = _006_;
  assign _073_ = _007_;
  assign _074_ = _008_;
  assign _075_ = _009_;
  assign _076_ = _010_;
  assign _077_ = _011_;
  assign _078_ = _012_;
  assign _079_ = _013_;
  assign _080_ = _014_;
  assign _081_ = _015_;
endmodule
