/* Generated by yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "TC.v:1.1-22.10" *)
module TC(clear, clk, rst, out);
  (* src = "TC.v:10.3-20.6" *)
  wire [2:0] _000_;
  (* src = "TC.v:10.3-20.6" *)
  wire _001_;
  (* src = "TC.v:10.3-20.6" *)
  wire _002_;
  (* src = "TC.v:10.3-20.6" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  (* src = "TC.v:4.11-4.16" *)
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  (* src = "TC.v:7.37-7.40" *)
  wire _011_;
  (* src = "TC.v:7.37-7.40" *)
  wire _012_;
  (* src = "TC.v:7.37-7.40" *)
  wire _013_;
  (* src = "TC.v:6.11-6.14" *)
  wire _014_;
  wire [2:0] _015_;
  wire [31:0] _016_;
  wire [31:0] _017_;
  (* src = "TC.v:17.16-17.23" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:266.22-266.23" *)
  wire [2:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:277.21-277.23" *)
  wire [31:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:282.21-282.26" *)
  wire [31:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:268.22-268.23" *)
  wire [31:0] _025_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [31:0] _026_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:272.12-272.14" *)
  wire _027_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:282.28-282.33" *)
  wire [31:0] _028_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:272.8-272.10" *)
  wire _029_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _030_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _031_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _032_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:215.8-215.10" *)
  wire _033_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:218.21-218.23" *)
  wire [31:0] _034_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [31:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.20-214.21" *)
  wire [31:0] _036_;
  wire [1023:0] _037_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.21-222.22" *)
  wire [31:0] _038_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.10-220.11" *)
  wire [31:0] _039_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:220.13-220.14" *)
  wire [31:0] _040_;
  (* force_downto = 32'd1 *)
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:222.18-222.19" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _041_;
  wire [31:0] _042_;
  wire [31:0] _043_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.42-286.49" *)
  wire [31:0] _044_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:279.31-279.37" *)
  wire [31:0] _045_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:279.26-279.45" *)
  wire [31:0] _046_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:288.13-288.20" *)
  wire [31:0] _047_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:289.13-289.25" *)
  wire [32:0] _048_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:231.18-231.27" *)
  wire _049_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _050_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _051_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _052_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _053_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _054_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _055_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _056_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _057_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _058_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _059_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _060_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _061_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _062_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _063_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _064_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _065_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _066_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _067_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _068_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _069_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _070_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _071_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _072_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _073_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _074_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _075_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _076_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _077_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _078_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _079_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _080_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _081_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _082_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _083_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _084_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _085_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _086_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _087_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _088_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _089_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _090_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _091_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _092_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _093_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _094_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _095_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _096_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _097_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _098_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _099_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _100_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _101_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _102_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _103_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _104_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _105_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _106_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _107_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _108_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _109_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _110_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _111_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _112_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _113_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _114_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _115_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _116_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _117_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _118_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _119_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _120_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _121_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _122_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _123_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _124_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _125_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _126_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _127_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _128_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _129_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _130_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _131_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _132_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _133_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _134_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _135_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _136_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _137_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _138_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _139_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _140_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _141_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _142_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _143_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _144_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _145_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _146_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _147_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _148_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _149_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _150_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _151_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _152_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _153_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _154_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _155_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _156_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _157_;
  (* src = "TC.v:17.16-17.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _158_;
  (* src = "TC.v:4.11-4.16" *)
  input clear;
  wire clear;
  (* src = "TC.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "TC.v:7.37-7.40" *)
  output [2:0] out;
  wire [2:0] out;
  (* src = "TC.v:6.11-6.14" *)
  input rst;
  wire rst;
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(_014_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__xnor2_1 _160_ (
    .A(_012_),
    .B(_011_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(_007_),
    .B(_008_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(_011_),
    .B(_007_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__a21bo_1 _163_ (
    .A1(_012_),
    .A2(_011_),
    .B1_N(_013_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand3b_1 _164_ (
    .A_N(_013_),
    .B(_012_),
    .C(_011_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a21oi_1 _165_ (
    .A1(_009_),
    .A2(_010_),
    .B1(_007_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(_014_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _167_ (
    .A(_014_),
    .Y(_006_)
  );
  (* src = "TC.v:10.3-20.6" *)
  sky130_fd_sc_hd__dfrtp_1 _168_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(out[0]),
    .RESET_B(_020_)
  );
  (* src = "TC.v:10.3-20.6" *)
  sky130_fd_sc_hd__dfrtp_1 _169_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(out[1]),
    .RESET_B(_019_)
  );
  (* src = "TC.v:10.3-20.6" *)
  sky130_fd_sc_hd__dfrtp_1 _170_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(out[2]),
    .RESET_B(_021_)
  );
  assign _030_ = _043_;
  assign _031_ = _042_;
  assign _032_ = _018_;
  assign _025_ = 32'd1;
  assign _022_ = out;
  assign _023_ = _024_;
  assign _026_ = _046_;
  assign _042_ = _047_;
  assign _018_ = _048_[31:0];
  assign _034_ = _043_;
  assign _035_ = _044_;
  assign _036_ = _042_;
  assign _037_ = 1024'h000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000070726f633b206f7074202d66617374;
  assign _038_ = _043_;
  assign _041_[0] = _042_[0];
  assign _040_ = 32'd32;
  assign _039_ = 32'd0;
  assign _028_ = 32'd1;
  assign _024_ = { 29'h00000000, out };
  assign _013_ = out[2];
  assign _012_ = out[1];
  assign _011_ = out[0];
  assign _014_ = rst;
  assign _019_ = _004_;
  assign _020_ = _005_;
  assign _007_ = clear;
  assign _000_[1] = _002_;
  assign _000_[0] = _001_;
  assign _021_ = _006_;
  assign _000_[2] = _003_;
endmodule
