/* Generated By Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "ALU.v:1.1-48.10" *)
module ALU(a, b, sel, out, neg, zero, agtb, aeqb, carry);
  (* src = "ALU.v:5.23-5.24" *)
  wire _000_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _001_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _002_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _003_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _004_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _005_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _006_;
  (* src = "ALU.v:5.23-5.24" *)
  wire _007_;
  (* src = "ALU.v:12.12-12.16" *)
  wire _008_;
  (* src = "ALU.v:11.12-11.16" *)
  wire _009_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _010_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _011_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _012_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _013_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _014_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _015_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _016_;
  (* src = "ALU.v:6.23-6.24" *)
  wire _017_;
  (* src = "ALU.v:13.16-13.21" *)
  wire _018_;
  (* src = "ALU.v:9.12-9.15" *)
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _151_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _152_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _153_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _154_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _155_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _156_;
  (* src = "ALU.v:8.28-8.31" *)
  wire _157_;
  (* src = "ALU.v:7.33-7.36" *)
  wire _158_;
  (* src = "ALU.v:7.33-7.36" *)
  wire _159_;
  (* src = "ALU.v:7.33-7.36" *)
  wire _160_;
  (* src = "ALU.v:10.12-10.16" *)
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire [3:0] _165_;
  wire [1:0] _166_;
  wire [3:0] _167_;
  wire [1:0] _168_;
  wire [2:0] _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire [3:0] _176_;
  wire [1:0] _177_;
  wire [3:0] _178_;
  wire [1:0] _179_;
  wire [3:0] _180_;
  wire [1:0] _181_;
  wire [3:0] _182_;
  wire [1:0] _183_;
  wire [3:0] _184_;
  wire [1:0] _185_;
  wire [3:0] _186_;
  wire [1:0] _187_;
  wire [3:0] _188_;
  wire [1:0] _189_;
  wire [3:0] _190_;
  wire [1:0] _191_;
  wire [3:0] _192_;
  wire [1:0] _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [2:0] _203_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _204_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _205_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [63:0] _206_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [63:0] _207_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [7:0] _208_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [7:0] _209_;
  (* src = "ALU.v:22.19-22.23" *)
  wire _210_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [8:0] _211_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 4 5 6" *)
  wire [7:0] _212_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _213_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [7:0] _214_;
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _215_;
  (* src = "ALU.v:0.0-0.0|ALU.v:29.5-45.12|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _216_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [8:0] _217_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [8:0] _218_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [8:0] _219_;
  (* force_downto = 32'd1 *)
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [8:0] _220_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _221_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _222_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _223_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _224_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _225_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _226_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _227_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _228_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _229_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _230_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _231_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _232_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _233_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _234_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _235_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _236_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _237_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _238_;
  (* src = "ALU.v:17.16-17.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _239_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _240_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _241_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _242_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _243_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _244_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _245_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _246_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _247_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _248_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _249_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _250_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _251_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _252_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _253_;
  (* src = "ALU.v:20.18-20.23|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _254_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _255_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _256_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _257_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _258_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _259_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _260_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _261_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _262_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _263_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _264_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _265_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _266_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _267_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _268_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _269_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _270_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _271_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _272_;
  (* src = "ALU.v:18.16-18.21|/usr/bin/../share/yosys/techmap.v:286.27-286.69|/usr/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _273_;
  (* src = "ALU.v:5.23-5.24" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "ALU.v:16.18-16.21" *)
  wire [8:0] add;
  (* src = "ALU.v:12.12-12.16" *)
  output aeqb;
  wire aeqb;
  (* src = "ALU.v:11.12-11.16" *)
  output agtb;
  wire agtb;
  (* src = "ALU.v:6.23-6.24" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "ALU.v:13.16-13.21" *)
  output carry;
  wire carry;
  (* src = "ALU.v:9.12-9.15" *)
  output neg;
  wire neg;
  (* src = "ALU.v:8.28-8.31" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "ALU.v:7.33-7.36" *)
  input [2:0] sel;
  wire [2:0] sel;
  (* src = "ALU.v:16.23-16.26" *)
  wire [8:0] sub;
  (* src = "ALU.v:10.12-10.16" *)
  output zero;
  wire zero;
  sky130_fd_sc_hd__xnor2_1 _274_ (
    .A(_047_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_101_),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(_006_),
    .B(_095_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _277_ (
    .A(_006_),
    .B(_016_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _278_ (
    .A(_104_),
    .SLEEP(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__o22ai_1 _279_ (
    .A1(_006_),
    .A2(_096_),
    .B1(_113_),
    .B2(_047_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a211oi_1 _280_ (
    .A1(_016_),
    .A2(_092_),
    .B1(_059_),
    .C1(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand4_1 _281_ (
    .A(_050_),
    .B(_056_),
    .C(_057_),
    .D(_061_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2b_1 _282_ (
    .A_N(_017_),
    .B(_007_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _283_ (
    .A(_017_),
    .SLEEP(_007_),
    .X(_063_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _284_ (
    .A(_062_),
    .SLEEP(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21o_1 _285_ (
    .A1(_048_),
    .A2(_058_),
    .B1(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__a31oi_1 _286_ (
    .A1(_048_),
    .A2(_058_),
    .A3(_064_),
    .B1(_118_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__maj3_1 _287_ (
    .A(_090_),
    .B(_016_),
    .C(_054_),
    .X(_067_)
  );
  sky130_fd_sc_hd__xnor2_1 _288_ (
    .A(_064_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand3_1 _289_ (
    .A(_007_),
    .B(_017_),
    .C(_104_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o221ai_1 _290_ (
    .A1(_007_),
    .A2(_096_),
    .B1(_113_),
    .B2(_064_),
    .C1(_069_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__a221o_1 _291_ (
    .A1(_017_),
    .A2(_092_),
    .B1(_095_),
    .B2(_007_),
    .C1(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__a221o_1 _292_ (
    .A1(_065_),
    .A2(_066_),
    .B1(_068_),
    .B2(_101_),
    .C1(_071_),
    .X(_019_)
  );
  sky130_fd_sc_hd__maj3_1 _293_ (
    .A(_001_),
    .B(_091_),
    .C(_097_),
    .X(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_124_),
    .B(_137_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand3b_1 _295_ (
    .A_N(_002_),
    .B(_012_),
    .C(_137_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__o211ai_1 _296_ (
    .A1(_072_),
    .A2(_073_),
    .B1(_074_),
    .C1(_136_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a31o_1 _297_ (
    .A1(_089_),
    .A2(_014_),
    .A3(_032_),
    .B1(_033_),
    .X(_076_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(_052_),
    .A2(_075_),
    .B1(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21ai_0 _299_ (
    .A1(_045_),
    .A2(_077_),
    .B1(_046_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(_062_),
    .A2(_078_),
    .B1(_063_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand3_1 _301_ (
    .A(_047_),
    .B(_052_),
    .C(_064_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor4_1 _302_ (
    .A(_099_),
    .B(_112_),
    .C(_073_),
    .D(_079_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__a21boi_0 _303_ (
    .A1(_007_),
    .A2(_017_),
    .B1_N(_065_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(_045_),
    .B(_064_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand3_1 _305_ (
    .A(_101_),
    .B(_062_),
    .C(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a31oi_1 _306_ (
    .A1(_047_),
    .A2(_051_),
    .A3(_064_),
    .B1(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__o21ai_0 _307_ (
    .A1(_020_),
    .A2(_079_),
    .B1(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _308_ (
    .A1(_118_),
    .A2(_080_),
    .B1(_084_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__or4_1 _309_ (
    .A(_151_),
    .B(_154_),
    .C(_155_),
    .D(_156_),
    .X(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(_152_),
    .B(_153_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor4b_1 _311_ (
    .A(_157_),
    .B(_019_),
    .C(_085_),
    .D_N(_086_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__clkinv_1 _312_ (
    .A(_158_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__clkinv_1 _313_ (
    .A(_003_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__clkinv_1 _314_ (
    .A(_004_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__clkinv_1 _315_ (
    .A(_006_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__clkinv_1 _316_ (
    .A(_011_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__and2_0 _317_ (
    .A(_159_),
    .B(_158_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(_159_),
    .B(_158_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand3_1 _319_ (
    .A(_160_),
    .B(_159_),
    .C(_087_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__o21ai_0 _320_ (
    .A1(_160_),
    .A2(_093_),
    .B1(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3b_1 _321_ (
    .A_N(_159_),
    .B(_158_),
    .C(_160_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _322_ (
    .A(_000_),
    .SLEEP(_010_),
    .X(_097_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _323_ (
    .A(_010_),
    .SLEEP(_000_),
    .X(_098_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _324_ (
    .A(_097_),
    .SLEEP(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_159_),
    .B(_158_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor3_1 _326_ (
    .A(_160_),
    .B(_159_),
    .C(_087_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _327_ (
    .A1(_100_),
    .A2(_101_),
    .B1(_099_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _328_ (
    .A(_000_),
    .B(_010_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor3b_1 _329_ (
    .A(_160_),
    .B(_158_),
    .C_N(_159_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_010_),
    .B(_092_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o21ai_0 _331_ (
    .A1(_000_),
    .A2(_096_),
    .B1(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a31oi_1 _332_ (
    .A1(_000_),
    .A2(_010_),
    .A3(_104_),
    .B1(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(_000_),
    .B(_095_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand3_1 _334_ (
    .A(_102_),
    .B(_107_),
    .C(_108_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_001_),
    .B(_011_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2b_1 _336_ (
    .A_N(_011_),
    .B(_001_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _337_ (
    .A(_001_),
    .B(_011_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__xor2_1 _338_ (
    .A(_001_),
    .B(_011_),
    .X(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _339_ (
    .A(_160_),
    .B(_100_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__o22ai_1 _340_ (
    .A1(_001_),
    .A2(_096_),
    .B1(_111_),
    .B2(_113_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a31oi_1 _341_ (
    .A1(_001_),
    .A2(_011_),
    .A3(_104_),
    .B1(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__o21ai_0 _342_ (
    .A1(_091_),
    .A2(_093_),
    .B1(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor3_1 _343_ (
    .A(_160_),
    .B(_159_),
    .C(_158_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__or3_1 _344_ (
    .A(_160_),
    .B(_159_),
    .C(_158_),
    .X(_118_)
  );
  sky130_fd_sc_hd__o21ai_0 _345_ (
    .A1(_103_),
    .A2(_111_),
    .B1(_117_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _346_ (
    .A1(_103_),
    .A2(_111_),
    .B1(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__xnor2_1 _347_ (
    .A(_098_),
    .B(_111_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22o_1 _348_ (
    .A1(_001_),
    .A2(_095_),
    .B1(_101_),
    .B2(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__or3_1 _349_ (
    .A(_116_),
    .B(_120_),
    .C(_122_),
    .X(_152_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _350_ (
    .A(_002_),
    .SLEEP(_012_),
    .X(_123_)
  );
  sky130_fd_sc_hd__xnor2_1 _351_ (
    .A(_002_),
    .B(_012_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _352_ (
    .A1(_098_),
    .A2(_112_),
    .B1(_110_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(_124_),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21a_1 _354_ (
    .A1(_124_),
    .A2(_125_),
    .B1(_101_),
    .X(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _355_ (
    .A1(_103_),
    .A2(_111_),
    .B1(_109_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xor2_1 _356_ (
    .A(_124_),
    .B(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _357_ (
    .A(_012_),
    .B(_092_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _358_ (
    .A1(_002_),
    .A2(_096_),
    .B1(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand3_1 _359_ (
    .A(_002_),
    .B(_012_),
    .C(_104_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21ai_0 _360_ (
    .A1(_113_),
    .A2(_124_),
    .B1(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a211oi_1 _361_ (
    .A1(_002_),
    .A2(_095_),
    .B1(_131_),
    .C1(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o21ai_0 _362_ (
    .A1(_118_),
    .A2(_129_),
    .B1(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a21o_1 _363_ (
    .A1(_126_),
    .A2(_127_),
    .B1(_135_),
    .X(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(_088_),
    .B(_013_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__xnor2_1 _365_ (
    .A(_003_),
    .B(_013_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a21oi_1 _366_ (
    .A1(_124_),
    .A2(_125_),
    .B1(_123_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__xnor2_1 _367_ (
    .A(_137_),
    .B(_138_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__maj3_1 _368_ (
    .A(_002_),
    .B(_012_),
    .C(_128_),
    .X(_140_)
  );
  sky130_fd_sc_hd__xor2_1 _369_ (
    .A(_137_),
    .B(_140_),
    .X(_141_)
  );
  sky130_fd_sc_hd__nor2_1 _370_ (
    .A(_003_),
    .B(_013_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_003_),
    .B(_096_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a31oi_1 _372_ (
    .A1(_160_),
    .A2(_013_),
    .A3(_092_),
    .B1(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__o32a_1 _373_ (
    .A1(_160_),
    .A2(_093_),
    .A3(_142_),
    .B1(_137_),
    .B2(_113_),
    .X(_145_)
  );
  sky130_fd_sc_hd__o2111ai_1 _374_ (
    .A1(_160_),
    .A2(_013_),
    .B1(_003_),
    .C1(_087_),
    .D1(_159_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand3_1 _375_ (
    .A(_144_),
    .B(_145_),
    .C(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _376_ (
    .A1(_101_),
    .A2(_139_),
    .B1(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o21ai_0 _377_ (
    .A1(_118_),
    .A2(_141_),
    .B1(_148_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__xnor2_1 _378_ (
    .A(_004_),
    .B(_014_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__xor2_1 _379_ (
    .A(_004_),
    .B(_014_),
    .X(_150_)
  );
  sky130_fd_sc_hd__maj3_1 _380_ (
    .A(_088_),
    .B(_013_),
    .C(_138_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _381_ (
    .A(_149_),
    .B(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__maj3_1 _382_ (
    .A(_003_),
    .B(_013_),
    .C(_140_),
    .X(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _383_ (
    .A(_150_),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__xnor2_1 _384_ (
    .A(_150_),
    .B(_022_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _385_ (
    .A(_014_),
    .B(_092_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _386_ (
    .A1(_004_),
    .A2(_096_),
    .B1(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _387_ (
    .A(_004_),
    .B(_014_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand3_1 _388_ (
    .A(_004_),
    .B(_014_),
    .C(_104_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o21ai_0 _389_ (
    .A1(_113_),
    .A2(_149_),
    .B1(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a211o_1 _390_ (
    .A1(_004_),
    .A2(_095_),
    .B1(_026_),
    .C1(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__a21oi_1 _391_ (
    .A1(_101_),
    .A2(_021_),
    .B1(_030_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o21ai_0 _392_ (
    .A1(_118_),
    .A2(_024_),
    .B1(_031_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand2b_1 _393_ (
    .A_N(_015_),
    .B(_005_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _394_ (
    .A(_015_),
    .SLEEP(_005_),
    .X(_033_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _395_ (
    .A(_032_),
    .SLEEP(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__maj3_1 _396_ (
    .A(_089_),
    .B(_014_),
    .C(_020_),
    .X(_035_)
  );
  sky130_fd_sc_hd__xnor2_1 _397_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _398_ (
    .A(_101_),
    .B(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21o_1 _399_ (
    .A1(_023_),
    .A2(_027_),
    .B1(_034_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a31oi_1 _400_ (
    .A1(_023_),
    .A2(_027_),
    .A3(_034_),
    .B1(_118_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _401_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _402_ (
    .A(_005_),
    .B(_015_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand3_1 _403_ (
    .A(_005_),
    .B(_015_),
    .C(_104_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o221ai_1 _404_ (
    .A1(_005_),
    .A2(_096_),
    .B1(_113_),
    .B2(_034_),
    .C1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a221oi_1 _405_ (
    .A1(_015_),
    .A2(_092_),
    .B1(_095_),
    .B2(_005_),
    .C1(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand3_1 _406_ (
    .A(_037_),
    .B(_040_),
    .C(_044_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_090_),
    .B(_016_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_090_),
    .B(_016_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2b_1 _409_ (
    .A(_045_),
    .B_N(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21o_1 _410_ (
    .A1(_038_),
    .A2(_041_),
    .B1(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand3_1 _411_ (
    .A(_038_),
    .B(_041_),
    .C(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand3_1 _412_ (
    .A(_117_),
    .B(_048_),
    .C(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o31ai_1 _413_ (
    .A1(_089_),
    .A2(_014_),
    .A3(_033_),
    .B1(_032_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__and2_0 _414_ (
    .A(_149_),
    .B(_034_),
    .X(_052_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _415_ (
    .A(_052_),
    .SLEEP(_020_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _416_ (
    .A(_051_),
    .B(_053_),
    .Y(_054_)
  );
  assign _192_[2:0] = _169_;
  assign _193_[0] = _170_;
  assign _203_[0] = 1'h0;
  assign { _206_[63:48], _206_[24], _206_[15:0] } = { add[7:0], sub[7:0], add[0], a, b };
  assign _208_[7:6] = _204_[2:1];
  assign { _211_[8:7], _211_[0] } = { 1'h0, add[8], _206_[40] };
  assign _217_[8] = 1'h1;
  assign _218_[7] = _218_[8];
  assign _219_[8] = 1'h1;
  assign _220_[8] = 1'h0;
  assign out[7] = neg;
  assign _160_ = sel[2];
  assign _159_ = sel[1];
  assign _158_ = sel[0];
  assign out[0] = _151_;
  assign out[1] = _152_;
  assign out[2] = _153_;
  assign out[3] = _154_;
  assign out[4] = _155_;
  assign out[5] = _156_;
  assign out[6] = _157_;
  assign neg = _019_;
  assign agtb = _009_;
  assign aeqb = _008_;
  assign carry = _018_;
  assign zero = _161_;
  assign _000_ = a[0];
  assign _001_ = a[1];
  assign _002_ = a[2];
  assign _003_ = a[3];
  assign _004_ = a[4];
  assign _005_ = a[5];
  assign _006_ = a[6];
  assign _007_ = a[7];
  assign _010_ = b[0];
  assign _011_ = b[1];
  assign _012_ = b[2];
  assign _013_ = b[3];
  assign _014_ = b[4];
  assign _015_ = b[5];
  assign _016_ = b[6];
  assign _017_ = b[7];
endmodule
